name: Benchmark

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  benchmark:
    name: Run benchmark
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install gnuplot
        run: sudo apt-get update && sudo apt-get install -y gnuplot

      - name: Run benchmark
        run: cargo bench

      - name: Save benchmark results
        uses: actions/upload-artifact@v3
        with:
          name: criterion-results
          path: target/criterion/
