name: Benchmark

on:
  pull_request:
    branches:
      - main

jobs:
  bench:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Benchmark
        run: cargo bench
