name: Publish to Creates

on:
  workflow_dispatch:
env:
  CARGO_TERM_COLOR: always
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build and Test
        run: |
          cargo build --workspace
          cargo test --workspace

      - name: Publish
        run: |
          cargo publish --token ${{ secrets.CARGO_TOKEN }} -p rico
          cargo publish --token ${{ secrets.CARGO_TOKEN }} -p rico-scan
